name: Deploy to NetSuite

on:
  push:
    branches: [main]

defaults:
  run:
    working-directory: netsuite-github-integration

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SDF_ACCOUNT_ID: ${{ secrets.SDF_ACCOUNT_ID }}
      SDF_CONSUMER_KEY: ${{ secrets.SDF_CONSUMER_KEY }}
      SDF_CONSUMER_SECRET: ${{ secrets.SDF_CONSUMER_SECRET }}
      SDF_TOKEN_ID: ${{ secrets.SDF_TOKEN_ID }}
      SDF_TOKEN_SECRET: ${{ secrets.SDF_TOKEN_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install SuiteCloud CLI
        run: npm install -g @oracle/suitecloud-cli --acceptsuitecloudsdklicense

      - name: Configure NetSuite Authentication
        run: |
          mkdir -p ~/.suitecloud
          echo '{' > ~/.suitecloud/config.json
          echo '  "defaultAuthId": "default",' >> ~/.suitecloud/config.json
          echo '  "auths": {' >> ~/.suitecloud/config.json
          echo '    "default": {' >> ~/.suitecloud/config.json
          echo '      "account": "'"$SDF_ACCOUNT_ID"'",' >> ~/.suitecloud/config.json
          echo '      "authType": "token",' >> ~/.suitecloud/config.json
          echo '      "tokenId": "'"$SDF_TOKEN_ID"'",' >> ~/.suitecloud/config.json
          echo '      "tokenSecret": "'"$SDF_TOKEN_SECRET"'",' >> ~/.suitecloud/config.json
          echo '      "consumerKey": "'"$SDF_CONSUMER_KEY"'",' >> ~/.suitecloud/config.json
          echo '      "consumerSecret": "'"$SDF_CONSUMER_SECRET"'"' >> ~/.suitecloud/config.json
          echo '    }' >> ~/.suitecloud/config.json
          echo '  }' >> ~/.suitecloud/config.json
          echo '}' >> ~/.suitecloud/config.json

      - name: Link Project to NetSuite
        run: echo '{ "defaultAuthId": "default" }' > .suitecloudrc.json

      - name: Debug: Show config files
        run: |
          echo ">>> .suitecloudrc.json"
          cat .suitecloudrc.json
          echo ">>> ~/.suitecloud/config.json"
          cat ~/.suitecloud/config.json
          suitecloud account:list

      - name: Deploy to NetSuite
        run: suitecloud project:deploy
