name: Deploy to NetSuite

on:
  push:
    branches: [main, develop]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Run NetSuite Deployer
      run: node deploy-script.js
      env:
        NETSUITE_ACCOUNT_ID: ${{ secrets.NETSUITE_ACCOUNT_ID }}
        SDF_CONSUMER_KEY: ${{ secrets.SDF_CONSUMER_KEY }}
        SDF_CONSUMER_SECRET: ${{ secrets.SDF_CONSUMER_SECRET }}
        SDF_TOKEN_ID: ${{ secrets.SDF_TOKEN_ID }}
        SDF_TOKEN_SECRET: ${{ secrets.SDF_TOKEN_SECRET }}
