name: Deploy to NetSuite (Token-Based)

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install SuiteCloud CLI (Legacy Version)
      run: npm install -g @oracle/suitecloud-cli@1.9.0 --acceptsuitecloudsdklicense
    
    - name: Set up authentication (Interactive)
      run: |
        # Create authentication configuration file
        mkdir -p ~/.suitecloud
        cat > ~/.suitecloud/credentials.json << EOF
        {
          "accountId": "${{ secrets.NETSUITE_ACCOUNT_ID }}",
          "authIds": {
            "github-actions": {
              "accountId": "${{ secrets.NETSUITE_ACCOUNT_ID }}",
              "tokenId": "${{ secrets.SDF_TOKEN_ID }}",
              "tokenSecret": "${{ secrets.SDF_TOKEN_SECRET }}",
              "consumerKey": "${{ secrets.SDF_CONSUMER_KEY }}",
              "consumerSecret": "${{ secrets.SDF_CONSUMER_SECRET }}"
            }
          }
        }
        EOF
    
    - name: Validate Project
      run: suitecloud project:validate
    
    - name: Deploy to NetSuite
      run: suitecloud project:deploy --authid github-actions