name: Deploy to NetSuite

on:
  push:
    branches: [main, develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Deploy to NetSuite
      run: node deploy-script.js
      env:
        NETSUITE_ACCOUNT_ID: ${{ secrets.NETSUIT_SDF_ACCOUNT_ID }}
        SDF_CONSUMER_KEY: ${{ secrets.SDF_CONSUMER_KEY }}
        SDF_CONSUMER_SECRET: ${{ secrets.SDF_CONSUMER_SECRET }}
        SDF_TOKEN_ID: ${{ secrets.SDF_TOKEN_ID }}
        SDF_TOKEN_SECRET: ${{ secrets.SDF_TOKEN_SECRET }}