name: Deploy to NetSuite (Docker)

on:
  push:
    branches: [main, develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy using NetSuite REST API
      run: |
        # Use Node.js script to deploy via REST API
        node deploy-script.js
      env:
        NETSUITE_ACCOUNT_ID: ${{ secrets.NETSUITE_ACCOUNT_ID }}
        SDF_CONSUMER_KEY: ${{ secrets.SDF_CONSUMER_KEY }}
        SDF_CONSUMER_SECRET: ${{ secrets.SDF_CONSUMER_SECRET }}
        SDF_TOKEN_ID: ${{ secrets.SDF_TOKEN_ID }}
        SDF_TOKEN_SECRET: ${{ secrets.SDF_TOKEN_SECRET }}