      - name: Link Project to NetSuite
        run: |
          echo '{ "defaultAuthId": "default" }' > .suitecloudrc.json

      - name: Debug auth and project config
        run: |
          echo ">>> Listing ~/.suitecloud/config.json"
          cat ~/.suitecloud/config.json

          echo ">>> Listing .suitecloudrc.json"
          cat .suitecloudrc.json

          echo ">>> Listing files in project root"
          ls -a .

          echo ">>> Checking available SuiteCloud auth accounts"
          suitecloud account:list

      - name: Deploy to NetSuite
        run: suitecloud project:deploy
